-- AlterTable
ALTER TABLE "BookContract" ADD COLUMN "reasoningTraceJson" TEXT;

-- AlterTable
ALTER TABLE "CharacterCastOption" ADD COLUMN "reasoningTraceJson" TEXT;

-- AlterTable
ALTER TABLE "CharacterCastOptionMember" ADD COLUMN "tier" TEXT;

-- AlterTable
ALTER TABLE "StoryMacroPlan" ADD COLUMN "reasoningTraceJson" TEXT;

-- AlterTable
ALTER TABLE "VolumePlan" ADD COLUMN "reasoningTraceJson" TEXT;

-- AlterTable
ALTER TABLE "VolumePlanVersion" ADD COLUMN "strategyReasoningTraceJson" TEXT;

-- AlterTable
ALTER TABLE "WorldConsistencyIssue" ADD COLUMN "suggestion" TEXT;

-- CreateTable
CREATE TABLE "BookAnalysisCharacter" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "analysisId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "aliases" TEXT,
    "role" TEXT,
    "profile" JSONB NOT NULL,
    "firstAppearanceLabel" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "BookAnalysisCharacter_analysisId_fkey" FOREIGN KEY ("analysisId") REFERENCES "BookAnalysis" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "BookAnalysisCharacterAppearance" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "characterId" TEXT NOT NULL,
    "sectionKey" TEXT,
    "excerpt" TEXT NOT NULL,
    "parsedTraits" JSONB,
    "orderIndex" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BookAnalysisCharacterAppearance_characterId_fkey" FOREIGN KEY ("characterId") REFERENCES "BookAnalysisCharacter" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "BookAnalysisCharacterAppearanceTerm" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "characterId" TEXT NOT NULL,
    "termCategory" TEXT NOT NULL,
    "termOriginal" TEXT NOT NULL,
    "termStandard" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "BookAnalysisCharacterMedia" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "characterId" TEXT NOT NULL,
    "mediaType" TEXT NOT NULL DEFAULT 'portrait',
    "url" TEXT NOT NULL,
    "prompt" TEXT,
    "style" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BookAnalysisCharacterMedia_characterId_fkey" FOREIGN KEY ("characterId") REFERENCES "BookAnalysisCharacter" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "RagRetrievalTrace" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "queryHash" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "novelId" TEXT,
    "worldId" TEXT,
    "timingJson" TEXT NOT NULL,
    "countsJson" TEXT NOT NULL,
    "hitsJson" TEXT,
    "optionsJson" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "GlobalReviewIssue" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "reviewRunId" TEXT NOT NULL,
    "issueNumber" INTEGER,
    "severity" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "fixDirection" TEXT NOT NULL,
    "affectedChapters" TEXT NOT NULL,
    "affectedChapterOrders" TEXT,
    "primaryFixChapter" TEXT,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "verificationFeedback" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "GlobalReviewIssue_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "LlmTokenUsage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "chapterId" TEXT,
    "promptName" TEXT NOT NULL,
    "stepType" TEXT,
    "provider" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "inputTokens" INTEGER NOT NULL,
    "outputTokens" INTEGER NOT NULL,
    "totalTokens" INTEGER NOT NULL,
    "latencyMs" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'recorded',
    "metadataJson" TEXT,
    "recordedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "BatchQueue" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "config" TEXT NOT NULL DEFAULT '{}',
    "totalChapters" INTEGER NOT NULL,
    "completedChapters" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "BatchQueue_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Batch" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "queueId" TEXT NOT NULL,
    "batchIndex" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "chapters" TEXT NOT NULL,
    "retryCount" INTEGER NOT NULL DEFAULT 0,
    "startedAt" DATETIME,
    "completedAt" DATETIME,
    "error" TEXT,
    CONSTRAINT "Batch_queueId_fkey" FOREIGN KEY ("queueId") REFERENCES "BatchQueue" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "NovelMaterial" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "content" TEXT NOT NULL,
    "wordCount" INTEGER NOT NULL DEFAULT 0,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "NovelMaterial_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CharacterConsistencyState" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "characterId" TEXT NOT NULL,
    "chapterNumber" INTEGER NOT NULL,
    "appearance" TEXT NOT NULL DEFAULT '{}',
    "personality" TEXT NOT NULL DEFAULT '{}',
    "abilities" TEXT NOT NULL DEFAULT '{}',
    "relationships" TEXT NOT NULL DEFAULT '{}',
    "currentStatus" TEXT,
    "location" TEXT,
    "sourceChapter" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CharacterConsistencyState_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "CharacterConsistencyState_characterId_fkey" FOREIGN KEY ("characterId") REFERENCES "Character" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CharacterConsistencyContradiction" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "chapterNumber" INTEGER NOT NULL,
    "characterId" TEXT NOT NULL,
    "characterName" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "severity" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "existingState" TEXT,
    "newState" TEXT,
    "suggestion" TEXT,
    "confidence" REAL NOT NULL DEFAULT 0,
    "resolved" BOOLEAN NOT NULL DEFAULT false,
    "resolvedNote" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "CharacterConsistencyContradiction_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "CharacterConsistencyScore" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "chapterNumber" INTEGER NOT NULL,
    "overallScore" INTEGER NOT NULL,
    "appearanceScore" INTEGER,
    "personalityScore" INTEGER,
    "abilityScore" INTEGER,
    "relationshipScore" INTEGER,
    "contradictionCount" INTEGER NOT NULL DEFAULT 0,
    "hardCount" INTEGER NOT NULL DEFAULT 0,
    "softCount" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CharacterConsistencyScore_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_APIKey" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "provider" TEXT NOT NULL,
    "displayName" TEXT,
    "key" TEXT,
    "model" TEXT,
    "baseURL" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "reasoningEnabled" BOOLEAN NOT NULL DEFAULT true,
    "concurrencyLimit" INTEGER NOT NULL DEFAULT 0,
    "requestIntervalMs" INTEGER NOT NULL DEFAULT 0,
    "rpm" INTEGER NOT NULL DEFAULT 60,
    "tpm" INTEGER NOT NULL DEFAULT 120000,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
INSERT INTO "new_APIKey" ("baseURL", "concurrencyLimit", "createdAt", "displayName", "id", "isActive", "key", "model", "provider", "reasoningEnabled", "requestIntervalMs", "updatedAt") SELECT "baseURL", "concurrencyLimit", "createdAt", "displayName", "id", "isActive", "key", "model", "provider", "reasoningEnabled", "requestIntervalMs", "updatedAt" FROM "APIKey";
DROP TABLE "APIKey";
ALTER TABLE "new_APIKey" RENAME TO "APIKey";
CREATE UNIQUE INDEX "APIKey_provider_key" ON "APIKey"("provider");
CREATE TABLE "new_BackgroundTask" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "progress" INTEGER NOT NULL DEFAULT 0,
    "params" TEXT NOT NULL DEFAULT '{}',
    "result" TEXT,
    "error" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "startedAt" DATETIME,
    "completedAt" DATETIME,
    "pausedAt" DATETIME,
    "cancelledAt" DATETIME,
    CONSTRAINT "BackgroundTask_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_BackgroundTask" ("cancelledAt", "completedAt", "createdAt", "error", "id", "novelId", "params", "pausedAt", "progress", "result", "startedAt", "status", "type", "updatedAt") SELECT "cancelledAt", "completedAt", "createdAt", "error", "id", "novelId", "params", "pausedAt", "progress", "result", "startedAt", "status", "type", "updatedAt" FROM "BackgroundTask";
DROP TABLE "BackgroundTask";
ALTER TABLE "new_BackgroundTask" RENAME TO "BackgroundTask";
CREATE INDEX "BackgroundTask_novelId_status_updatedAt_idx" ON "BackgroundTask"("novelId", "status", "updatedAt");
CREATE INDEX "BackgroundTask_status_updatedAt_idx" ON "BackgroundTask"("status", "updatedAt");
CREATE TABLE "new_Character" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "gender" TEXT NOT NULL DEFAULT 'unknown',
    "castRole" TEXT,
    "storyFunction" TEXT,
    "relationToProtagonist" TEXT,
    "personality" TEXT,
    "background" TEXT,
    "development" TEXT,
    "identityLabel" TEXT,
    "factionLabel" TEXT,
    "stanceLabel" TEXT,
    "powerLevel" TEXT,
    "realm" TEXT,
    "currentLocation" TEXT,
    "availability" TEXT,
    "prohibitionsJson" TEXT NOT NULL DEFAULT '[]',
    "outerGoal" TEXT,
    "innerNeed" TEXT,
    "fear" TEXT,
    "wound" TEXT,
    "misbelief" TEXT,
    "secret" TEXT,
    "moralLine" TEXT,
    "firstImpression" TEXT,
    "appearance" TEXT,
    "physique" TEXT,
    "attireStyle" TEXT,
    "signatureDetail" TEXT,
    "voiceTexture" TEXT,
    "presenceImpression" TEXT,
    "arcStart" TEXT,
    "arcMidpoint" TEXT,
    "arcClimax" TEXT,
    "arcEnd" TEXT,
    "currentState" TEXT,
    "currentGoal" TEXT,
    "exitStatus" TEXT NOT NULL DEFAULT 'active',
    "exitNote" TEXT,
    "exitChapterId" TEXT,
    "tier" TEXT NOT NULL DEFAULT 'named',
    "lastEvolvedAt" DATETIME,
    "novelId" TEXT NOT NULL,
    "baseCharacterId" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "Character_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_Character" ("appearance", "arcClimax", "arcEnd", "arcMidpoint", "arcStart", "attireStyle", "availability", "background", "baseCharacterId", "castRole", "createdAt", "currentGoal", "currentLocation", "currentState", "development", "exitChapterId", "exitNote", "exitStatus", "factionLabel", "fear", "firstImpression", "gender", "id", "identityLabel", "innerNeed", "lastEvolvedAt", "misbelief", "moralLine", "name", "novelId", "outerGoal", "personality", "physique", "powerLevel", "presenceImpression", "prohibitionsJson", "realm", "relationToProtagonist", "role", "secret", "signatureDetail", "stanceLabel", "storyFunction", "updatedAt", "voiceTexture", "wound") SELECT "appearance", "arcClimax", "arcEnd", "arcMidpoint", "arcStart", "attireStyle", "availability", "background", "baseCharacterId", "castRole", "createdAt", "currentGoal", "currentLocation", "currentState", "development", "exitChapterId", "exitNote", "exitStatus", "factionLabel", "fear", "firstImpression", "gender", "id", "identityLabel", "innerNeed", "lastEvolvedAt", "misbelief", "moralLine", "name", "novelId", "outerGoal", "personality", "physique", "powerLevel", "presenceImpression", "prohibitionsJson", "realm", "relationToProtagonist", "role", "secret", "signatureDetail", "stanceLabel", "storyFunction", "updatedAt", "voiceTexture", "wound" FROM "Character";
DROP TABLE "Character";
ALTER TABLE "new_Character" RENAME TO "Character";
CREATE INDEX "Character_novelId_idx" ON "Character"("novelId");
CREATE INDEX "Character_baseCharacterId_idx" ON "Character"("baseCharacterId");
CREATE TABLE "new_Checkpoint" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "novelId" TEXT NOT NULL,
    "chapterIndex" INTEGER NOT NULL,
    "data" TEXT NOT NULL DEFAULT '{}',
    "isPinned" BOOLEAN NOT NULL DEFAULT false,
    "label" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Checkpoint_novelId_fkey" FOREIGN KEY ("novelId") REFERENCES "Novel" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_Checkpoint" ("chapterIndex", "createdAt", "data", "id", "isPinned", "label", "novelId") SELECT "chapterIndex", "createdAt", "data", "id", "isPinned", "label", "novelId" FROM "Checkpoint";
DROP TABLE "Checkpoint";
ALTER TABLE "new_Checkpoint" RENAME TO "Checkpoint";
CREATE INDEX "Checkpoint_novelId_createdAt_idx" ON "Checkpoint"("novelId", "createdAt");
CREATE TABLE "new_PromptTemplateVersion" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "overrideId" TEXT NOT NULL,
    "versionNo" INTEGER NOT NULL,
    "templateJson" TEXT NOT NULL,
    "contextRefsJson" TEXT NOT NULL,
    "compiledHash" TEXT NOT NULL,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PromptTemplateVersion_overrideId_fkey" FOREIGN KEY ("overrideId") REFERENCES "PromptTemplateOverride" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_PromptTemplateVersion" ("compiledHash", "contextRefsJson", "createdAt", "id", "notes", "overrideId", "templateJson", "versionNo") SELECT "compiledHash", "contextRefsJson", "createdAt", "id", "notes", "overrideId", "templateJson", "versionNo" FROM "PromptTemplateVersion";
DROP TABLE "PromptTemplateVersion";
ALTER TABLE "new_PromptTemplateVersion" RENAME TO "PromptTemplateVersion";
CREATE INDEX "PromptTemplateVersion_overrideId_versionNo_idx" ON "PromptTemplateVersion"("overrideId", "versionNo");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE INDEX "BookAnalysisCharacter_analysisId_name_idx" ON "BookAnalysisCharacter"("analysisId", "name");

-- CreateIndex
CREATE INDEX "BookAnalysisCharacter_analysisId_role_idx" ON "BookAnalysisCharacter"("analysisId", "role");

-- CreateIndex
CREATE INDEX "BookAnalysisCharacterAppearance_characterId_orderIndex_idx" ON "BookAnalysisCharacterAppearance"("characterId", "orderIndex");

-- CreateIndex
CREATE INDEX "BookAnalysisCharacterAppearanceTerm_characterId_termCategory_idx" ON "BookAnalysisCharacterAppearanceTerm"("characterId", "termCategory");

-- CreateIndex
CREATE INDEX "BookAnalysisCharacterAppearanceTerm_termCategory_termStandard_idx" ON "BookAnalysisCharacterAppearanceTerm"("termCategory", "termStandard");

-- CreateIndex
CREATE INDEX "BookAnalysisCharacterMedia_characterId_idx" ON "BookAnalysisCharacterMedia"("characterId");

-- CreateIndex
CREATE INDEX "RagRetrievalTrace_tenantId_createdAt_idx" ON "RagRetrievalTrace"("tenantId", "createdAt");

-- CreateIndex
CREATE INDEX "RagRetrievalTrace_queryHash_idx" ON "RagRetrievalTrace"("queryHash");

-- CreateIndex
CREATE INDEX "GlobalReviewIssue_novelId_reviewRunId_idx" ON "GlobalReviewIssue"("novelId", "reviewRunId");

-- CreateIndex
CREATE INDEX "GlobalReviewIssue_novelId_status_idx" ON "GlobalReviewIssue"("novelId", "status");

-- CreateIndex
CREATE INDEX "GlobalReviewIssue_primaryFixChapter_status_idx" ON "GlobalReviewIssue"("primaryFixChapter", "status");

-- CreateIndex
CREATE UNIQUE INDEX "GlobalReviewIssue_novelId_issueNumber_key" ON "GlobalReviewIssue"("novelId", "issueNumber");

-- CreateIndex
CREATE INDEX "LlmTokenUsage_novelId_recordedAt_idx" ON "LlmTokenUsage"("novelId", "recordedAt");

-- CreateIndex
CREATE INDEX "LlmTokenUsage_novelId_stepType_recordedAt_idx" ON "LlmTokenUsage"("novelId", "stepType", "recordedAt");

-- CreateIndex
CREATE INDEX "LlmTokenUsage_provider_recordedAt_idx" ON "LlmTokenUsage"("provider", "recordedAt");

-- CreateIndex
CREATE INDEX "LlmTokenUsage_promptName_recordedAt_idx" ON "LlmTokenUsage"("promptName", "recordedAt");

-- CreateIndex
CREATE INDEX "LlmTokenUsage_recordedAt_idx" ON "LlmTokenUsage"("recordedAt");

-- CreateIndex
CREATE INDEX "BatchQueue_novelId_status_idx" ON "BatchQueue"("novelId", "status");

-- CreateIndex
CREATE INDEX "BatchQueue_status_updatedAt_idx" ON "BatchQueue"("status", "updatedAt");

-- CreateIndex
CREATE INDEX "Batch_queueId_batchIndex_idx" ON "Batch"("queueId", "batchIndex");

-- CreateIndex
CREATE INDEX "Batch_queueId_status_idx" ON "Batch"("queueId", "status");

-- CreateIndex
CREATE INDEX "NovelMaterial_novelId_enabled_idx" ON "NovelMaterial"("novelId", "enabled");

-- CreateIndex
CREATE INDEX "NovelMaterial_novelId_sortOrder_idx" ON "NovelMaterial"("novelId", "sortOrder");

-- CreateIndex
CREATE INDEX "CharacterConsistencyState_novelId_characterId_idx" ON "CharacterConsistencyState"("novelId", "characterId");

-- CreateIndex
CREATE INDEX "CharacterConsistencyState_novelId_chapterNumber_idx" ON "CharacterConsistencyState"("novelId", "chapterNumber");

-- CreateIndex
CREATE INDEX "CharacterConsistencyState_characterId_createdAt_idx" ON "CharacterConsistencyState"("characterId", "createdAt");

-- CreateIndex
CREATE INDEX "CharacterConsistencyContradiction_novelId_chapterNumber_idx" ON "CharacterConsistencyContradiction"("novelId", "chapterNumber");

-- CreateIndex
CREATE INDEX "CharacterConsistencyContradiction_novelId_severity_idx" ON "CharacterConsistencyContradiction"("novelId", "severity");

-- CreateIndex
CREATE INDEX "CharacterConsistencyContradiction_characterId_idx" ON "CharacterConsistencyContradiction"("characterId");

-- CreateIndex
CREATE INDEX "CharacterConsistencyContradiction_type_idx" ON "CharacterConsistencyContradiction"("type");

-- CreateIndex
CREATE INDEX "CharacterConsistencyScore_novelId_chapterNumber_idx" ON "CharacterConsistencyScore"("novelId", "chapterNumber");

-- CreateIndex
CREATE INDEX "CharacterConsistencyScore_novelId_createdAt_idx" ON "CharacterConsistencyScore"("novelId", "createdAt");

