import type { BookAnalysisCharacterProfile } from "@ai-novel/shared";
import { prisma } from "../../../db/prisma";
import { AppError } from "../../../middleware/errorHandler";

export interface CharacterExtractionInput {
  analysisId: string;
  name: string;
  aliases?: string[];
  role?: string;
  profile: BookAnalysisCharacterProfile;
  firstAppearanceLabel?: string;
}

export interface CharacterUpdateInput {
  name?: string;
  aliases?: string[];
  role?: string;
  profile?: Partial<BookAnalysisCharacterProfile>;
  firstAppearanceLabel?: string | null;
}

export class BookAnalysisCharacterService {
  async listCharacters(analysisId: string) {
    return prisma.bookAnalysisCharacter.findMany({
      where: { analysisId },
      orderBy: [{ isAutoGenerated: "asc" }, { name: "asc" }],
    });
  }

  async getCharacter(characterId: string) {
    const character = await prisma.bookAnalysisCharacter.findUnique({
      where: { id: characterId },
      include: {
        appearances: { orderBy: [{ orderIndex: "asc" }] },
        media: { orderBy: [{ createdAt: "desc" }] },
      },
    });
    if (!character) {
      throw new AppError("Book analysis character not found.", 404);
    }
    return character;
  }

  async createCharacter(input: CharacterExtractionInput) {
    const analysis = await prisma.bookAnalysis.findUnique({
      where: { id: input.analysisId },
      select: { id: true, status: true },
    });
    if (!analysis) {
      throw new AppError("Book analysis not found.", 404);
    }
    const existing = await prisma.bookAnalysisCharacter.findFirst({
      where: { analysisId: input.analysisId, name: input.name },
    });
    if (existing) {
      throw new AppError("Character with this name already exists in this analysis.", 409);
    }
    return prisma.bookAnalysisCharacter.create({
      data: {
        analysisId: input.analysisId,
        name: input.name,
        aliases: input.aliases ? JSON.stringify(input.aliases) : null,
        role: input.role ?? null,
        profile: input.profile as any,
        firstAppearanceLabel: input.firstAppearanceLabel ?? null,
      },
    });
  }

  async updateCharacter(characterId: string, input: CharacterUpdateInput) {
    const character = await prisma.bookAnalysisCharacter.findUnique({
      where: { id: characterId },
    });
    if (!character) {
      throw new AppError("Book analysis character not found.", 404);
    }
    const profile = input.profile
      ? { ...(character.profile as any), ...input.profile }
      : undefined;
    return prisma.bookAnalysisCharacter.update({
      where: { id: characterId },
      data: {
        ...(input.name ? { name: input.name } : {}),
        ...(input.aliases !== undefined ? { aliases: JSON.stringify(input.aliases) } : {}),
        ...(input.role !== undefined ? { role: input.role } : {}),
        ...(profile ? { profile: profile as any } : {}),
        ...(input.firstAppearanceLabel !== undefined
          ? { firstAppearanceLabel: input.firstAppearanceLabel }
          : {}),
      },
    });
  }

  async deleteCharacter(characterId: string) {
    const character = await prisma.bookAnalysisCharacter.findUnique({
      where: { id: characterId },
    });
    if (!character) {
      throw new AppError("Book analysis character not found.", 404);
    }
    await prisma.bookAnalysisCharacter.delete({ where: { id: characterId } });
  }

  async extractCharactersFromSections(analysisId: string): Promise<number> {
    const sections = await prisma.bookAnalysisSection.findMany({
      where: {
        analysisId,
        status: "succeeded",
        sectionKey: "character_system",
      },
      select: { aiContent: true, editedContent: true, title: true },
    });
    if (sections.length === 0) {
      return 0;
    }
    const characterContent = sections
      .map((s) => s.editedContent?.trim() || s.aiContent?.trim() || "")
      .filter(Boolean)
      .join("\n\n");
    if (!characterContent.trim()) {
      return 0;
    }
    const existingChars = await prisma.bookAnalysisCharacter.findMany({
      where: { analysisId, isAutoGenerated: true },
      select: { id: true },
    });
    if (existingChars.length > 0) {
      await prisma.bookAnalysisCharacter.deleteMany({
        where: { id: { in: existingChars.map((c) => c.id) } },
      });
    }
    return this.parseCharactersFromText(analysisId, characterContent);
  }

  private async parseCharactersFromText(analysisId: string, text: string): Promise<number> {
    const lines = text.split("\n").filter((l) => l.trim());
    const characterMap = new Map<string, { name: string; role: string; description: string }>();

    let currentName: string | null = null;
    let currentRole = "";
    let currentDesc = "";

    for (const line of lines) {
      const headingMatch = line.match(/^#{1,3}\s*(.+)/);
      if (headingMatch) {
        if (currentName && currentDesc.trim()) {
          characterMap.set(currentName, { name: currentName, role: currentRole, description: currentDesc.trim() });
        }
        const headerText = headingMatch[1].trim();
        const roleMatch = headerText.match(/^(.+?)(?:\s*[（(](.+?)[）)])?\s*$/);
        currentName = roleMatch?.[1]?.trim() ?? headerText;
        currentRole = roleMatch?.[2]?.trim() ?? "";
        currentDesc = "";
        continue;
      }
      currentDesc += line + "\n";
    }
    if (currentName && currentDesc.trim()) {
      characterMap.set(currentName, { name: currentName, role: currentRole, description: currentDesc.trim() });
    }

    let created = 0;
    for (const [name, info] of characterMap) {
      if (name.length > 50) continue;
      try {
        await prisma.bookAnalysisCharacter.create({
          data: {
            analysisId,
            name,
            role: info.role || null,
            profile: this.buildDefaultProfile(info.description) as any,
            isAutoGenerated: true,
            firstAppearanceLabel: info.description.slice(0, 100),
          },
        });
        created++;
      } catch {
        // skip duplicates
      }
    }
    return created;
  }

  private buildDefaultProfile(description: string): BookAnalysisCharacterProfile {
    return {
      appearance: { summary: "", features: [], clothing: [] },
      personality: { traits: [], temperament: "", archetype: "" },
      background: { history: "", origin: "", occupation: "" },
      motivation: { goals: [], drives: "", conflicts: [] },
      relationships: { allies: [], rivals: [], lovers: [], mentors: [] },
      arc: { startingPoint: "", transformation: "", endingPoint: "" },
      speech: { catchphrases: [], tone: "", vocabulary: "" },
      behavior: { patterns: [], habits: [], quirks: [] },
      symbolism: { themes: [], metaphors: [], narrativeRole: "" },
      weaknesses: { flaws: [], fears: [], limitations: [] },
      skills: { talents: [], expertise: [], powers: [] },
      socialStatus: { class: "", influence: "", reputation: "" },
      rawDescription: description,
    };
  }
}
