import type {
  BookAnalysisCharacter,
  BookAnalysisCharacterAppearance,
  BookAnalysisCharacterAppearanceTerm,
  BookAnalysisCharacterMedia,
} from "@ai-novel/shared";

/**
 * Serialize Prisma raw rows to their shared-type representations for Character entities.
 */

export interface CharacterRow {
  id: string;
  analysisId: string;
  name: string;
  aliases: string | null;
  role: string | null;
  profile: any;
  firstAppearanceLabel: string | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface AppearanceRow {
  id: string;
  characterId: string;
  sectionKey: string | null;
  excerpt: string;
  parsedTraits: any;
  orderIndex: number;
  createdAt: Date;
}

export interface AppearanceTermRow {
  id: string;
  characterId: string;
  termCategory: string;
  termOriginal: string;
  termStandard: string;
  createdAt: Date;
}

export interface MediaRow {
  id: string;
  characterId: string;
  mediaType: string;
  url: string;
  prompt: string | null;
  style: string | null;
  createdAt: Date;
}

export function serializeCharacter(row: CharacterRow): BookAnalysisCharacter {
  return {
    id: row.id,
    analysisId: row.analysisId,
    name: row.name,
    aliases: row.aliases ? safeJsonParse<string[]>(row.aliases) : null,
    role: row.role,
    profile: typeof row.profile === "object" ? row.profile : safeJsonParse(row.profile),
    firstAppearanceLabel: row.firstAppearanceLabel,
    isAutoGenerated: row.isAutoGenerated,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  };
}

export function serializeCharacterDetail(
  character: CharacterRow,
  appearances: AppearanceRow[],
  media: MediaRow[],
): BookAnalysisCharacter {
  return {
    ...serializeCharacter(character),
    appearances: appearances.map(serializeAppearance),
    media: media.map(serializeMedia),
  };
}

export function serializeAppearance(row: AppearanceRow): BookAnalysisCharacterAppearance {
  return {
    id: row.id,
    characterId: row.characterId,
    sectionKey: row.sectionKey,
    excerpt: row.excerpt,
    parsedTraits: typeof row.parsedTraits === "object" ? row.parsedTraits : null,
    orderIndex: row.orderIndex,
    createdAt: row.createdAt.toISOString(),
  };
}

export function serializeAppearanceTerm(row: AppearanceTermRow): BookAnalysisCharacterAppearanceTerm {
  return {
    id: row.id,
    characterId: row.characterId,
    termCategory: row.termCategory,
    termOriginal: row.termOriginal,
    termStandard: row.termStandard,
    createdAt: row.createdAt.toISOString(),
  };
}

export function serializeMedia(row: MediaRow): BookAnalysisCharacterMedia {
  return {
    id: row.id,
    characterId: row.characterId,
    mediaType: row.mediaType,
    url: row.url,
    prompt: row.prompt,
    style: row.style,
    createdAt: row.createdAt.toISOString(),
  };
}

function safeJsonParse<T>(raw: string | null | undefined, fallback?: T): T | null {
  if (!raw) {
    return fallback ?? null;
  }
  try {
    return JSON.parse(raw) as T;
  } catch {
    return fallback ?? null;
  }
}
