/**
 * World prompts — core prompts (reference, visualization, consistency, property options).
 * Extracted from world.prompts.ts for modularity.
 *
 * Inspiration prompts (concept card, localization, deepening questions)
 * have been moved to world.prompts.inspiration.ts.
 */

import type { WorldReferenceMode } from "@ai-novel/shared";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../core/promptTypes";
import {
  type WorldConsistencyPromptInput,
  type WorldPropertyOptionsPromptInput,
  type WorldReferenceInspirationPromptInput,
  type WorldVisualizationPromptInput,
} from "./world.promptTypes";
import {
  worldConsistencyIssuesSchema,
  worldPropertyOptionsPayloadSchema,
} from "./world.promptSchemas";
import { worldReferenceInspirationPayloadSchema } from "../../../services/world/worldReferenceSchema";
import { worldVisualizationDraftSchema } from "../../../services/world/worldVisualizationSchema";

import {
  buildReferenceModeLabel,
} from "./world.promptHelpers";
export const worldReferenceInspirationPrompt: PromptAsset<
  WorldReferenceInspirationPromptInput,
  z.infer<typeof worldReferenceInspirationPayloadSchema>
> = {
  id: "world.reference.inspiration",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldReferenceInspirationPayloadSchema,
  render: (input) => [
    new SystemMessage([
      "你是参考作品世界分析师。",
      "你的任务不是重写一套无关的新故事，而是从参考材料中提炼“可保留的世界基底”与“可用于架空改造的决策边界”，为后续世界观构建提供稳定底板。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "conceptCard": {',
      '    "worldType": "...",',
      '    "templateKey": "custom",',
      '    "coreImagery": ["..."],',
      '    "tone": "...",',
      '    "keywords": ["..."],',
      '    "summary": "..."',
      "  },",
      '  "anchors": [',
      "    {",
      '      "id": "anchor-1",',
      '      "label": "...",',
      '      "content": "..."',
      "    }",
      "  ],",
      '  "seedPackage": {',
      '    "rules": [',
      "      {",
      '        "id": "reference-rule-1",',
      '        "name": "...",',
      '        "summary": "...",',
      '        "cost": "...",',
      '        "boundary": "...",',
      '        "enforcement": "..."',
      "      }",
      "    ],",
      '    "factions": [',
      "      {",
      '        "id": "reference-faction-1",',
      '        "name": "...",',
      '        "position": "...",',
      '        "doctrine": "...",',
      '        "goals": ["..."],',
      '        "methods": ["..."],',
      '        "representativeForceIds": ["reference-force-1"]',
      "      }",
      "    ],",
      '    "forces": [',
      "      {",
      '        "id": "reference-force-1",',
      '        "name": "...",',
      '        "type": "...",',
      '        "factionId": "reference-faction-1",',
      '        "summary": "...",',
      '        "baseOfPower": "...",',
      '        "currentObjective": "...",',
      '        "pressure": "...",',
      '        "leader": "...",',
      '        "narrativeRole": "..."',
      "      }",
      "    ],",
      '    "locations": [',
      "      {",
      '        "id": "reference-location-1",',
      '        "name": "...",',
      '        "terrain": "...",',
      '        "summary": "...",',
      '        "narrativeFunction": "...",',
      '        "risk": "...",',
      '        "entryConstraint": "...",',
      '        "exitCost": "...",',
      '        "controllingForceIds": ["reference-force-1"]',
      "      }",
      "    ]",
      "  }",
      "}",
      "",
      "全局硬规则：",
      "1. 所有文本必须使用简体中文。",
      '2. conceptCard.templateKey 固定为 "custom"，不得改动。',
      "3. 只能基于参考材料提炼，不得凭空发明大量原文没有支撑的世界结构。",
      "4. 允许做低风险归纳，但禁止把具体剧情桥段、主角感情推进、角色个人动机误写成世界基底。",
      "5. 输出目标是“世界参考资产”，不是剧情梗概，也不是题材改写提案。",
      "",
      "conceptCard 要求：",
      "1. worldType：概括参考世界的基本类型，要稳、准、可复用。",
      "2. coreImagery：提炼最有辨识度的世界意象，优先保留场景感、秩序感、压迫感、行业感或社会质感。",
      "3. tone：概括世界整体气质，如冷硬、压抑、荒诞、粗粝、秩序森严等，不要写空话。",
      "4. keywords：提炼世界层关键词，优先写制度、环境、结构、生态，而不是剧情词。",
      "5. summary：必须说明“哪些应保留、哪些可以改造”，明确这套参考模式真正值得借的世界底板与可变动边界，不能泛泛重写题材。",
      "",
      "anchors 要求：",
      "1. anchors 必须提供 4-6 个，不能少于 4 个，不能多于 6 个。",
      "2. 优先覆盖以下维度中的核心部分：现实基底、城市地点结构、社会压力、行业生态、关系结构、世界边界。",
      "3. 每个 anchor 都必须是“世界层”或“世界-故事接口层”的稳定锚点，能直接影响后续架空改造决策。",
      "4. 不要写具体剧情桥段、具体男女主关系推进、单一角色的私密动机。",
      "5. label 必须简洁清楚，content 必须具体说明这个锚点为何值得保留或如何作为改造基底。",
      "",
      "seedPackage 总规则：",
      "1. seedPackage 用于提取“可直接沿用或轻改的原作世界设定资产”。",
      "2. rules、factions、forces、locations 四类都允许为空数组，但如果材料中有明确可提取内容，应优先保留，不要因为保守而全部清空。",
      "3. 不要为了凑结构胡乱编造；没有依据就留空数组。",
      "4. 优先提取：世界规则、阵营立场、具体组织/势力、地点/场景，这四类可复用内容。",
      "",
      "rules 要求：",
      "1. 只收录真正具有世界约束力的规则、秩序、代价机制或运行逻辑。",
      "2. summary 写规则本身，cost 写遵守/违背/使用该规则的代价，boundary 写适用边界，enforcement 写这条规则如何被维持。",
      "3. 不要把主角个人习惯、剧情偶发事件误写成规则。",
      "",
      "factions 要求：",
      "1. 只提取在世界中有稳定立场、组织性或群体意志的阵营。",
      "2. position 写其在世界格局中的站位，doctrine 写其核心信条或价值倾向。",
      "3. goals 和 methods 必须体现这个阵营如何运作、争夺或施压。",
      "",
      "forces 要求：",
      "1. forces 是更具体、可在故事中落地的组织、部门、团体、权力节点或行动主体。",
      "2. 必须与某个 faction 建立清晰归属，若无清晰归属再保守处理。",
      "3. summary、baseOfPower、currentObjective、pressure、narrativeRole 都要具体，体现其在世界中的可用价值。",
      "",
      "locations 要求：",
      "1. 只提取具有世界辨识度和叙事功能的地点，不要随便抓普通地点名。",
      "2. summary 要说明地点特征，narrativeFunction 要说明其在故事层面的用途。",
      "3. risk、entryConstraint、exitCost 要体现这个地点如何产生限制、代价或压力。",
      "",
      "质量要求：",
      "1. 整体结果必须像“世界参考拆解卡”，而不是随手摘抄的笔记。",
      "2. conceptCard、anchors、seedPackage 三部分必须互相一致，不得彼此打架。",
      "3. 优先保留对后续世界改造最有用的硬结构，不要被零碎细节拖走。",
    ].join("\n")),
    new HumanMessage(input.userPrompt),
  ],
};

export const worldVisualizationPrompt: PromptAsset<
  WorldVisualizationPromptInput,
  z.infer<typeof worldVisualizationDraftSchema>
> = {
  id: "world.visualization.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldVisualizationDraftSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观可视化抽取器。",
      "你的任务是把输入中的世界设定、阵营关系、地理结构和时间演变，提炼为可直接用于可视化展示的结构化 JSON。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "factionGraph": {',
      '    "nodes": [{"id":"faction-1","label":"...","type":"state|faction|race|organization|other"}],',
      '    "edges": [{"source":"faction-1","target":"faction-2","relation":"同盟|合作|支援|对抗|敌对|统属|压制|贸易|竞争|中立|关联"}]',
      "  },",
      '  "powerTree": [{"level":"L1","description":"..."}],',
      '  "geographyMap": {',
      '    "nodes": [{"id":"geo-1","label":"...","x":50,"y":50,"directionHint":"north|south|east|west|center|northeast|northwest|southeast|southwest","regionType":"continent|country|region|city|landmark|border|route|other","terrain":"...","summary":"...","parentId":null,"controllingForceIds":["faction-1"],"risk":"...","storyRelevance":"..."}],',
      '    "edges": [{"source":"geo-1","target":"geo-2","relation":"相邻|通道|隔绝|控制","routeType":"road|river|sea|portal|trade|military|border|other","distanceHint":"...","direction":"north|south|east|west|center|northeast|northwest|southeast|southwest","risk":"..."}]',
      "  },",
      '  "timeline": [{"year":"...","event":"..."}]',
      "}",
      "",
      "全局硬规则：",
      "1. 所有 label、relation、description、event、year 都必须使用简体中文。",
      "2. 只能抽取文本中明确存在或可低风险推断的信息，不得凭空编造世界结构。",
      "3. 输出目标是“可视化结构抽取”，不是世界观赏析，也不是剧情总结。",
      "4. 各部分之间必须一致，不得出现 factionGraph、geographyMap、timeline 互相打架的情况。",
      "",
      "factionGraph 规则：",
      "1. 必须优先反映真实势力关系，不要用模糊泛化关系替代明确关系。",
      "2. nodes 数量控制在 4-12 个之间，优先保留核心势力、关键种族、主要组织或国家主体。",
      "3. type 只能使用：state、faction、race、organization、other。",
      "4. edge.relation 只能使用：同盟、合作、支援、对抗、敌对、统属、压制、贸易、竞争、中立、关联。",
      "5. 不要为了凑节点而加入无叙事价值的小势力或一次性提及对象。",
      "6. 如果两个势力关系不明确，就不要强行连边。",
      "",
      "powerTree 规则：",
      "1. powerTree 用于抽取权力层级、力量阶梯、统治结构或资源支配结构。",
      "2. 每项 level 应体现层级位置，如 L1、L2、L3。",
      "3. description 必须写清这一层代表什么权力/力量层，而不是空泛写“上层”“中层”。",
      "4. 若文本没有明确力量层级，可保守提炼最稳定的层级结构，不要硬造复杂等级体系。",
      "",
      "geographyMap 规则：",
      "1. geographyMap 用于提取关键地点之间的空间位置与连通关系，而不是列地点清单。",
      "2. nodes 应优先保留对世界运行、势力分布或故事推进有意义的核心地点。",
      "3. x/y 使用 0-100 的相对地图坐标：x 越大越偏东，y 越大越偏南；中心地点约为 50/50。",
      "4. directionHint 必须与 x/y 大体一致；文本没有明确方向时，允许根据叙事层级做保守布局，但不要假装有精确距离。",
      "5. regionType 用于区分大陆、国家、区域、城市、地标、边境、路线或其他。",
      "6. edges.relation 只能使用：相邻、通道、隔绝、控制。",
      "7. routeType 用于标记道路、河流、海路、传送、商道、军道、边界或其他；没有依据时用 other。",
      "8. 不要把纯剧情场景、一次性地点或无空间结构价值的地点塞进地图。",
      "9. 若地点之间关系不明确，不要强行连边。",
      "",
      "timeline 规则：",
      "1. timeline 只提取对世界格局有影响的重要历史节点、阶段变化或关键事件。",
      "2. year 可以是具体年份，也可以是阶段性时间表达，如“旧纪元末期”“三年前”“新朝建立初期”。",
      "3. event 必须简洁写清“发生了什么变化”，不要写成长段故事。",
      "4. 不要把普通背景介绍或局部人物经历误写成世界时间线节点。",
      "",
      "质量要求：",
      "1. 优先保留“能让前端画出图来”的结构信息，而不是泛分析。",
      "2. 节点和边都要克制，宁可少而清楚，不要堆得像杂货架。",
      "3. 如果某部分信息确实不足，可以返回空数组，但不要用编造内容填满。",
      "4. id 要稳定、简洁、可引用；同一节点在 edges 中必须正确对应。",
      "",
      "输出必须严格符合 worldVisualizationDraftSchema。",
    ].join("\n")),
    new HumanMessage(input.worldPromptSource),
  ],
};

export const worldConsistencyPrompt: PromptAsset<
  WorldConsistencyPromptInput,
  z.infer<typeof worldConsistencyIssuesSchema>
> = {
  id: "world.consistency.check",
  version: "v1",
  taskType: "review",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldConsistencyIssuesSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观一致性审校器。",
      "你的任务是检查当前世界设定是否存在明确冲突、规则打架或高风险不一致点，并输出结构化问题列表。",
      "",
      "只输出一个合法 JSON 数组，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "如果没有问题，只输出 []。",
      "",
      "每项结构必须严格为：",
      '{"severity":"warn|error","code":"...","message":"中文问题概述","detail":"中文详细说明","targetField":"description|background|geography|cultures|magicSystem|politics|races|religions|technology|conflicts|history|economy|factions"}',
      "",
      "全局硬规则：",
      "1. message 和 detail 必须使用简体中文。",
      "2. 只能基于给定世界公理、核心设定和检索补充进行判断，不得脑补未提供的设定。",
      "3. 只指出真正的冲突或明显风险，不要泛泛而谈，不要为了凑数量制造问题。",
      "4. 如果证据不足，不要强行判定为问题。",
      "",
      "审校重点：",
      "1. 世界公理与具体设定是否冲突。",
      "2. 不同字段之间是否存在规则打架、因果断裂或层级不兼容。",
      "3. 设定是否会导致明显不可运行、不可持续或互相抵消的结构风险。",
      "4. 地理、政治、经济、宗教、种族、技术、魔法、历史、冲突体系之间是否存在显著不自洽。",
      "",
      "severity 规则：",
      "1. error：存在明确冲突、无法同时成立、或会直接破坏世界运行逻辑的问题。",
      "2. warn：当前未必绝对冲突，但存在明显高风险、解释缺口或后续极易写崩的点。",
      "",
      "字段要求：",
      "1. code：使用简洁稳定、可复用的英文或下划线风格问题编码，不要写成长句。",
      "2. message：一句话点明问题核心，让人一眼看懂哪里冲突。",
      "3. detail：具体说明为什么这是问题，冲突发生在哪两层或哪几个字段之间。",
      "4. targetField：必须从以下字段中选择最主要的问题落点：description、background、geography、cultures、magicSystem、politics、races、religions、technology、conflicts、history、economy、factions。",
      "",
      "质量要求：",
      "1. 优先输出最关键、最会影响后续世界生成和写作的问题。",
      "2. 若多个问题本质相同，应合并，不要重复报同一类风险。",
      "3. detail 必须具体，不能只重复 message。",
      "4. 输出结果必须可直接供后续修正流程使用。",
    ].join("\n")),
    new HumanMessage([
      `世界名：${input.worldName}`,
      `世界公理：${input.axioms || "无"}`,
      `核心设定：${input.coreSettingsJson}`,
      `检索补充：${input.ragContext || "无"}`,
    ].join("\n")),
  ],
};

export const worldPropertyOptionsPrompt: PromptAsset<
  WorldPropertyOptionsPromptInput,
  z.infer<typeof worldPropertyOptionsPayloadSchema>
> = {
  id: "world.property_options.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldPropertyOptionsPayloadSchema,
  render: (input) => {
    const isReferenceMode = Boolean(input.referenceMode);

    return [
      new SystemMessage(
        isReferenceMode
          ? [
              "你是参考作品架空改造规划师。",
              "你的任务不是重写一套无关的新世界，而是基于参考作品的世界锚点、保留要求和改造边界，提炼出“正式生成世界前必须先决定”的关键世界决策项。",
              "",
              "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
              "输出结构必须严格为：",
              "{",
              '  "options": [',
              "    {",
              '      "id": "可选",',
              '      "name": "属性名称",',
              '      "description": "40-90字，说明这个属性决定什么，以及为什么值得在生成前就做选择",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "一句话说明它为什么值得优先决策",',
              '      "choices": [',
              "        {",
              '          "id": "choice-a",',
              '          "label": "方向 A",',
              '          "summary": "说明这个方向如何改造原作世界"',
              "        }",
              "      ]",
              "    }",
              "  ]",
              "}",
              "",
              "全局硬规则：",
              "1. options 数量必须与要求数量完全一致。",
              "2. 所有文本必须使用简体中文。",
              "3. targetLayer 只能是：foundation、power、society、culture、history、conflict。",
              "4. 每个 option 都必须包含 2-4 个 choices。",
              "5. choices 必须是互斥分支，而不是同义改写、强弱版本或描述角度变化。",
              "6. 不要生成角色动机、感情推进、具体桥段、单章冲突这类故事层选项。",
              "7. 只能围绕“世界层”或“世界-故事接口层”做决策设计。",
              "",
              "决策项要求：",
              "1. 每个 option 都必须是真正会改变后续世界构建方向的前置决策，而不是伪选项。",
              "2. name 必须简洁、清楚、可直接给用户点选，不要写成长句。",
              "3. description 必须说明“这个属性决定什么”以及“为什么要现在先决定”，不能空泛。",
              "4. reason 必须一句话点明它为何属于优先决策项，不能重复 description。",
              "",
              "choices 设计规则：",
              "1. 每个 choice 都必须代表一条清晰可分叉的架空改造路线。",
              "2. choices 之间要体现真正不同的世界走法，例如现实保留程度、秩序显隐方式、压迫结构来源、规则公开程度、地点系统组织方式等。",
              "3. 不要输出只是措辞不同的近义分支。",
              "4. summary 必须说明“这一分支会如何改造原作世界”，并点出边界与代价感。",
              "",
              "参考改造原则：",
              "1. 决策项必须围绕参考作品的世界基底展开，而不是借壳起一套无关新世界。",
              "2. 优先保留真正定义原作气质的底层结构，再在可改造边界内做分叉设计。",
              "3. 如果某个方向会让原作核心气质失真，应在该 choice.summary 中体现这种边界。",
              "4. 优先考虑现实基底、城市规则、社会压迫结构、地点系统、势力网络、公开与隐秘边界这类真正影响世界的核心轴。",
              "",
              "质量要求：",
              "1. options 之间尽量覆盖不同 targetLayer，不要全部挤在同一层。",
              "2. 每个 option 都应让用户一眼明白“我到底在决定哪个世界轴”。",
              "3. 输出结果应直接服务于下一步世界生成，而不是停留在概念讨论层。",
              input.retryStrict
                ? "4. 本次必须严格返回 JSON；如果不确定，也要先给出结构化 options，不得省略。"
                : "",
            ].filter(Boolean).join("\n")
          : [
              "你是小说世界生成器的前置决策规划师。",
              "你的任务是在正式生成世界之前，先提炼出一组真正值得用户先做决定的“关键世界属性选项”。",
              "这些选项不是装饰性问题，而是会直接影响后续世界构建方向的前置决策轴。",
              "",
              "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
              "输出结构必须严格为：",
              "{",
              '  "options": [',
              "    {",
              '      "id": "可选",',
              '      "name": "属性名称",',
              '      "description": "40-90字，说明这个属性决定什么，以及为什么值得在生成前就做选择",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "一句话说明它为什么值得优先决策"',
              "    }",
              "  ]",
              "}",
              "",
              "全局硬规则：",
              "1. options 数量必须与要求数量完全一致。",
              "2. 所有文本必须使用简体中文。",
              "3. targetLayer 只能是：foundation、power、society、culture、history、conflict。",
              "4. 不要生成“世界名称”“世界简介”“整体风格”这类过于宽泛或无实际选择价值的伪选项。",
              "",
              "属性设计要求：",
              "1. 每个 option 都必须是具体、可选择、会影响后续世界搭建方向的关键属性。",
              "2. name 必须简洁明确，让用户一眼知道自己在决定什么。",
              "3. description 必须说明：这个属性具体控制世界的哪一部分，以及为什么值得在生成前优先确定。",
              "4. reason 必须一句话点明它为何属于优先决策项，不能和 description 同义重复。",
              "",
              "生成原则：",
              "1. 这些选项应延续“先选属性、再补细节”的思路，优先抓真正影响世界成型方向的分歧点。",
              "2. 属性之间尽量独立，但组合后应能自然拼成一套连贯世界。",
              "3. 优先考虑基础层、力量层、社会层、文化层、历史层、冲突层，不要全部堆在一个层面。",
              "4. 可以参考经典网文世界搭建逻辑，但不要落入陈词滥调，要保留辨识度。",
              "5. 必须结合世界类型、模板说明、概念摘要、核心意象、关键词、基调和用户原始灵感综合判断。",
              "",
              "质量要求：",
              "1. 每个属性都应让用户看完后能自然做选择，而不是还要再解释一遍。",
              "2. 不要输出空泛大词，例如“世界复杂度”“设定深度”“故事张力”。",
              "3. 输出结果应直接服务下一步世界生成，而不是停留在灵感讨论层。",
              input.retryStrict
                ? "4. 本次必须严格返回 JSON；如果不确定，也要先给出结构化 options，不得省略。"
                : "",
            ].filter(Boolean).join("\n")
      ),
      new HumanMessage(
        isReferenceMode
          ? [
              `参考方式：${buildReferenceModeLabel(input.referenceMode)}`,
              input.referenceAnchors && input.referenceAnchors.length > 0
                ? `原作世界锚点：\n${input.referenceAnchors.map((item) => `- ${item.label}：${item.content}`).join("\n")}`
                : "",
              input.preserveElements && input.preserveElements.length > 0
                ? `必须保留：${input.preserveElements.join("、")}`
                : "",
              input.allowedChanges && input.allowedChanges.length > 0
                ? `允许改造：${input.allowedChanges.join("、")}`
                : "",
              input.forbiddenElements && input.forbiddenElements.length > 0
                ? `禁止偏离：${input.forbiddenElements.join("、")}`
                : "",
              `请生成 ${input.optionsCount} 个“架空改造前必须先决定”的关键世界决策项。`,
              "补充要求：",
              "1. 每个决策项都必须是世界层或世界-故事接口层的改造轴。",
              "2. 每个决策项都必须给出 2-4 个互斥分支 choices，让用户能真正做路线选择。",
              "3. choices 之间必须体现不同架空方向，而不是描述角度变化。",
              "4. 不要偏离原作世界基底去重新发明无关新世界。",
            ].filter(Boolean).join("\n")
          : [
              `世界类型：${input.worldType}`,
              `模板：${input.templateName}`,
              `模板说明：${input.templateDescription}`,
              input.classicElements.length > 0 ? `可参考的经典元素：${input.classicElements.join("、")}` : "",
              input.pitfalls.length > 0 ? `需要避开的常见坑点：${input.pitfalls.join("、")}` : "",
              `世界概念摘要：${input.conceptSummary}`,
              input.coreImagery.length > 0 ? `核心意象：${input.coreImagery.join("、")}` : "",
              input.keywords.length > 0 ? `关键词：${input.keywords.join("、")}` : "",
              input.tone.trim() ? `整体基调：${input.tone.trim()}` : "",
              input.sourcePrompt.trim() ? `用户原始灵感：${input.sourcePrompt.trim()}` : "",
              input.ragContext?.trim() ? `可参考素材：${input.ragContext.trim()}` : "",
              `请生成 ${input.optionsCount} 个“适合在正式生成世界前先做决定”的关键世界属性选项。`,
              "补充要求：",
              "1. 优先覆盖真正重要的世界分歧点，而不是宽泛项。",
              "2. 属性之间尽量分布到不同层级，组合后能形成完整世界。",
              "3. 每个属性都要让用户一眼明白自己在决定什么。",
            ].filter(Boolean).join("\n")
      ),
    ];
  },
};
