/**
 * chapterRuntime.ts — Barrel re-export for chapter runtime types.
 *
 * Split from the original monolithic file (REQ-7020). The actual schema
 * definitions live in:
 *   - chapterCore.ts     — base enums, core runtime data schemas
 *   - chapterStyle.ts    — style contract & length control schemas
 *   - chapterContext.ts   — prompt context & generation context package
 *   - generationPackage.ts — acceptance, audit report, orchestration package
 *
 * This file re-exports everything to preserve backward compatibility.
 */

// Base enums and core runtime data schemas
export {
  llmProviderSchema,
  auditTypeSchema,
  auditSeveritySchema,
  auditIssueStatusSchema,
  chapterGenerationStateSchema,
  storyPlanRoleSchema,
  payoffLedgerScopeTypeSchema,
  payoffLedgerStatusSchema,
  payoffLedgerNormalizedStatusSchema,
  styleBindingTargetTypeSchema,
  styleDetectionRuleTypeSchema,
  antiAiSeveritySchema,
  styleContractSectionKeySchema,
  styleContractMaturitySchema,
  styleContractIssueCategorySchema,
  styleContractViolationSourceSchema,
  characterCandidateStatusSchema,
  dynamicCharacterRiskLevelSchema,
  auditModeSchema,
  contextBlockTierSchema,
  chapterRuntimeRequestSchema,
  runtimeChapterSchema,
  runtimePlanSceneSchema,
  runtimePlanSchema,
  runtimeCharacterSchema,
  runtimeCreativeDecisionSchema,
  runtimeAuditIssueSchema,
  runtimeCharacterStateSchema,
  runtimeRelationStateSchema,
  runtimeInformationStateSchema,
  runtimeForeshadowStateSchema,
  runtimeOpenConflictSchema,
  runtimePayoffLedgerSourceRefSchema,
  runtimePayoffLedgerEvidenceSchema,
  runtimePayoffLedgerRiskSignalSchema,
  runtimePayoffLedgerItemSchema,
  runtimePayoffLedgerSummarySchema,
  runtimeStateSnapshotSchema,
  runtimeContinuationSchema,
  runtimeQualityScoreSchema,
  type ChapterRuntimeRequest,
  type RuntimeChapter,
  type RuntimePlanScene,
  type RuntimePlan,
  type RuntimeCharacter,
  type RuntimeCreativeDecision,
  type RuntimeAuditIssue,
  type RuntimeStateSnapshot,
  type RuntimeOpenConflict,
  type RuntimeContinuation,
  type RuntimePayoffLedgerSourceRef,
  type RuntimePayoffLedgerEvidence,
  type RuntimePayoffLedgerRiskSignal,
  type RuntimePayoffLedgerItem,
  type RuntimePayoffLedgerSummary,
  type RuntimeCharacterResourceContext,
  type RuntimeQualityScore,
  // Character dynamics
  runtimeCharacterCandidateSchema,
  runtimeCharacterVolumeAssignmentSchema,
  runtimeCharacterFactionTrackSchema,
  runtimeCharacterRelationStageSchema,
  runtimeDynamicCharacterOverviewItemSchema,
  runtimeDynamicCharacterCurrentVolumeSchema,
  runtimeDynamicCharacterOverviewSchema,
  type RuntimeCharacterCandidate,
  type RuntimeCharacterVolumeAssignment,
  type RuntimeCharacterFactionTrack,
  type RuntimeCharacterRelationStage,
  type RuntimeDynamicCharacterOverviewItem,
  type RuntimeDynamicCharacterCurrentVolume,
} from "./chapterCore";

// Backward-compat: original chapterRuntime.ts exported RuntimeDynamicCharacterOverview
export type { DynamicCharacterOverview as RuntimeDynamicCharacterOverview } from "./chapterCore";

// Style contract & length control
export {
  runtimeStyleRuleBlockSchema,
  runtimeStyleContractSectionSchema,
  runtimeStyleContractSchema,
  runtimeCompiledStylePromptBlocksSchema,
  runtimeStyleProfileSummarySchema,
  runtimeStyleBindingSchema,
  runtimeStyleContextSchema,
  styleDetectionViolationSchema,
  styleDetectionReportSchema,
  runtimeStyleReviewSchema,
  runtimeSceneGenerationResultSchema,
  runtimeSceneRoundResultSchema,
  runtimeSceneGenerationWithRoundsSchema,
  runtimeLengthControlSchema,
  type RuntimeStyleContractSection,
  type RuntimeStyleContract,
  type RuntimeCompiledStylePromptBlocks,
  type RuntimeStyleBinding,
  type RuntimeStyleContext,
  type RuntimeStyleDetectionViolation,
  type RuntimeStyleDetectionReport,
  type RuntimeStyleReview,
  type RuntimeSceneGenerationResult,
  type RuntimeSceneRoundResult,
  type RuntimeLengthControl,
} from "./chapterStyle";

// Prompt context & generation context package
export {
  promptBudgetProfileSchema,
  contextGatingDecisionSchema,
  chapterChangeFlagsSchema,
  tokenBudgetPolicySchema,
  bookContractContextSchema,
  macroConstraintContextSchema,
  volumeKeyMilestoneGuardSchema,
  volumeWindowContextSchema,
  chapterMissionContextSchema,
  chapterBoundaryContractSchema,
  chapterExecutionObligationContractSchema,
  chapterExecutionObligationKindSchema,
  chapterExecutionObligationCoverageStatusSchema,
  chapterExecutionMissingObligationSchema,
  chapterExecutionObligationCoverageSchema,
  chapterFailureClassificationCodeSchema,
  chapterFailureClassificationSchema,
  chapterCharacterBehaviorGuideSchema,
  chapterRelationStageGuideSchema,
  chapterCandidateGuardSchema,
  chapterCharacterHardFactSchema,
  chapterWriteContextSchema,
  chapterReviewContextSchema,
  chapterRepairIssueSchema,
  chapterRepairContextSchema,
  generationContextPackageSchema,
  type PromptBudgetProfile,
  type AuditMode,
  type ContextBlockTier,
  type ContextGatingDecision,
  type ChapterChangeFlags,
  type TokenBudgetPolicy,
  type BookContractContext,
  type MacroConstraintContext,
  type VolumeWindowContext,
  type ChapterMissionContext,
  type ChapterBoundaryContract,
  type ChapterExecutionObligationContract,
  type ChapterExecutionObligationKind,
  type ChapterExecutionMissingObligation,
  type ChapterExecutionObligationCoverage,
  type ChapterFailureClassification,
  type ChapterCharacterBehaviorGuide,
  type ChapterRelationStageGuide,
  type ChapterCandidateGuard,
  type ChapterCharacterHardFact,
  type ChapterWriteContext,
  type ChapterReviewContext,
  type ChapterRepairIssue,
  type ChapterRepairContext,
  type GenerationContextPackage,
} from "./chapterContext";

// Acceptance, audit report & orchestration package
export {
  chapterAcceptanceStatusSchema,
  chapterAcceptanceContinuePolicySchema,
  chapterAcceptanceRepairDirectiveSchema,
  chapterAcceptanceRepairabilitySchema,
  chapterAcceptanceAssetSyncRecommendationSchema,
  runtimeAuditReportSchema,
  chapterRuntimePackageSchema,
  type ChapterAcceptanceStatus,
  type ChapterAcceptanceContinuePolicy,
  type ChapterAcceptanceRepairDirective,
  type ChapterAcceptanceRepairability,
  type ChapterAcceptanceAssetSyncRecommendation,
  type RuntimeAuditReport,
  type ChapterRuntimePackage,
} from "./generationPackage";
