const test = require("node:test");
const assert = require("node:assert/strict");

test("BookAnalysisCharacterSerializers", async (t) => {
  const serializers = require("../../../dist/services/bookAnalysis/bookAnalysisCharacter/BookAnalysisCharacterSerializers");
  const baseDate = new Date("2026-07-15T10:00:00Z");
  const defaultProfile = {
    appearance: { summary: "Tall and slender", features: ["sharp eyes"], clothing: [] },
    personality: { traits: ["calm"], temperament: "cool", archetype: "hero" },
    background: { history: "orphan", origin: "unknown", occupation: "swordsman" },
    motivation: { goals: ["revenge"], drives: "justice", conflicts: [] },
    relationships: { allies: [], rivals: [], lovers: [], mentors: [] },
    arc: { startingPoint: "", transformation: "", endingPoint: "" },
    speech: { catchphrases: [], tone: "", vocabulary: "" },
    behavior: { patterns: [], habits: [], quirks: [] },
    symbolism: { themes: [], metaphors: [], narrativeRole: "" },
    weaknesses: { flaws: [], fears: [], limitations: [] },
    skills: { talents: [], expertise: [], powers: [] },
    socialStatus: { class: "", influence: "", reputation: "" },
  };

  const characterRow = {
    id: "char-1",
    analysisId: "analysis-1",
    name: "主角云清",
    aliases: JSON.stringify(["清风", "清"]),
    role: "protagonist",
    profile: defaultProfile,
    firstAppearanceLabel: "Chapter 1",
    isAutoGenerated: true,
    createdAt: baseDate,
    updatedAt: baseDate,
  };

  await t.test("serializes character row correctly", () => {
    const result = serializers.serializeCharacter(characterRow);
    assert.equal(result.id, "char-1");
    assert.equal(result.analysisId, "analysis-1");
    assert.equal(result.name, "主角云清");
    assert.deepEqual(result.aliases, ["清风", "清"]);
    assert.equal(result.role, "protagonist");
    assert.ok(result.profile);
    assert.equal(result.firstAppearanceLabel, "Chapter 1");
    assert.equal(result.isAutoGenerated, true);
    assert.equal(result.createdAt, baseDate.toISOString());
  });

  await t.test("serializes appearance row", () => {
    const row = {
      id: "app-1",
      characterId: "char-1",
      sectionKey: "ch1",
      excerpt: "他一袭白衣",
      parsedTraits: { clothing: "白衣" },
      orderIndex: 0,
      createdAt: baseDate,
    };
    const result = serializers.serializeAppearance(row);
    assert.equal(result.id, "app-1");
    assert.equal(result.excerpt, "他一袭白衣");
    assert.deepEqual(result.parsedTraits, { clothing: "白衣" });
    assert.equal(result.orderIndex, 0);
  });

  await t.test("serializes appearance term row", () => {
    const row = {
      id: "term-1",
      characterId: "char-1",
      termCategory: "hair",
      termOriginal: "黑色头发",
      termStandard: "黑发",
      createdAt: baseDate,
    };
    const result = serializers.serializeAppearanceTerm(row);
    assert.equal(result.id, "term-1");
    assert.equal(result.termCategory, "hair");
    assert.equal(result.termOriginal, "黑色头发");
    assert.equal(result.termStandard, "黑发");
  });

  await t.test("serializes media row", () => {
    const row = {
      id: "media-1",
      characterId: "char-1",
      mediaType: "portrait",
      url: "https://example.com/portrait.png",
      prompt: "Generate a portrait",
      style: "anime",
      createdAt: baseDate,
    };
    const result = serializers.serializeMedia(row);
    assert.equal(result.id, "media-1");
    assert.equal(result.mediaType, "portrait");
    assert.equal(result.url, "https://example.com/portrait.png");
    assert.equal(result.prompt, "Generate a portrait");
    assert.equal(result.style, "anime");
  });
});
